### ISSUE TITLE
bots.setVariable is not a function

### ISSUE THREAD

**Issue by s-mv** [mrfishie/js-chatbot#1]
I did everything as per as your tutorial, but the console says:
bots.setVariable is not a function [line 113: bots.js]

**Comment by mrfishie** [comment]
Hi @ShreerangV, thanks for checking out the repo!

It looks like you're probably passing in an incorrect bot name to `Bots.sendMessage`. If you set `Bots.util.debug` to `true` somewhere earlier in your code, you'll likely see a message in the console saying the bot with the specified name could not be found. This might be because you haven't added the bot with `Bots.push`, or have spelled the bot name incorrectly.

Regardless, hopefully you've noticed this library isn't maintained anymore, especially considering the last commit was 4 years ago... If you're finding it useful and would be happy to continue maintaining it, let me know and I can add you as a contributor to this repo :)

**Comment by s-mv** [comment]
Hi! @mrfishie then can you validate this:
<pre>window.onload = function (){

Bots.push({
    "name": "Wireless",
    "precatch": function(text) {
        return text;
    },
    "actions": [{
        "catch": ["hello"],
        "response": "Hello!"
    },
    {
        "catch": ["*how are you*"],
        "response": [
            "I'm good thanks! What about you?",
            "Um.. alright, I guess.",
            "I don't feel well."
        ]
    }
    ],
    "postcatch": function(text) {
        return text;
    },
    
    "functions": {},
    "synonyms": [],
    "variables": {}
});
$(function() {
    var input = $("input"), username = "me";
    $("form").submit(function(e) {
        var r = Bots.sendMessage("MyBot", input.val(), { "USER": username });
        $("<p style='display:none;'></p>").appendTo("div").text("[" + username + "] " + input.val()).fadeIn("fast", toBottom);
        input.val("");
        
        setTimeout(function() {
            for (var i = 0; i < r.length; i++) {
                $("<p style='display:none;'></p>").appendTo("div").text(r[i]).fadeIn("fast", toBottom);
            }
        }, Math.random() * 1000);
        
        e.preventDefault();
        return false;
    });
});

function toBottom() {
    $("<div>").scrollTop($("div").get("scrollHeight"));
}
var out = Bots.sendMessage("Wireless", "hello", { "USER": "me" });
console.log(out);
}</pre>

**Comment by mrfishie** [comment]
Please read your code again, specifically this line:

```js
var r = Bots.sendMessage("MyBot", input.val(), { "USER": username });
```

You've registered a bot called "Wireless", the name you've passed in here ("MyBot") isn't valid.

**Comment by s-mv** [comment]
Oh. Pesky silly bug! Thanks a lot friend.
